name: Auto Daily Update

on:
  schedule:
    - cron: '0 22,7 * * *' # 每日台灣時間 06:00 與 15:00 自動執行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pandas requests lxml html5lib
      - name: Run script
        run: python main.py
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add history_data.json
          git commit -m "Auto update chips data" || exit 0
          git push
